---
- name: System Configuration
  hosts: all
  tags:
    - config
    - system
  tasks:

    #- enable ssh (disabled for now, new personal preference)
    # - name: SSH | check if remote login status is on
    #   sudo: yes
    #   command: systemsetup -getremotelogin
    #   register: remotelogin
    #   changed_when: "remotelogin.stdout.startswith('Remote Login: On') == False"

    # - name: SSH | enable remote login
    #   sudo: yes
    #   command: systemsetup -setremotelogin on
    #   when: remotelogin|changed

    # Enable the OSX default firewall
    # https://coderwall.com/p/zt8aqa
    - name: System | enable firewall
      become: yes
      osx_defaults: domain=/Library/Preferences/com.apple.alf
                    key=globalstate
                    type=int
                    value=1
      # notify: restart firewall

    # Note: due to Apple weirdness, this value is expected to be a string rather
    # then a bool, despite the fact it's a boolean value!, e.g. "true" as a str.
    - name: System | disable network .DS_Store
      osx_defaults: domain=com.apple.desktopservices
                    key=DSDontWriteNetworkStores
                    type=string
                    value=true


    # TODO: check for full disk encryption! (maybe dont manually install)
    # TODO: set recovery message in case of lost device (yeah right)
    # https://github.com/boxen/puppet-osx/blob/master/manifests/recovery_message.pp

  handlers:
    - name: restart firewall
      become: yes
      shell: >
        launchctl unload /System/Library/LaunchDaemons/com.apple.alf.agent.plist
        launchctl load /System/Library/LaunchDaemons/com.apple.alf.agent.plist



# - name: Account Configuration
#   hosts: all
#   tags:
#     - config
#     - account
#     - xtra
#   vars:
#     # Preferred location to find your user avatar and where to store it on the
#     # system.  If file is not found, will ignore tasks related to setting user
#     # avatar gracefully.
#     avatar:
#       src:  "./files/avatars/{{ansible_user_id}}.jpg"
#       dest: "~/Library/User Pictures/{{ansible_user_id}}.jpg"
#   tasks:


- name: UI Configuration
  hosts: all
  tags: ui
  vars:
    dock:
      showhidden: true
      tilesize: 42
      autohide: true
  handlers:
    # - name:    killall Finder
    #   command: killall Finder
    - name:    killall Dock
      command: killall Dock
    # - name:    killall SystemUIServer
    #   command: killall SystemUIServer
  tasks:
    - name: UI | Dock | dim hidden apps is {{ dock.showhidden }}
      osx_defaults: domain=com.apple.dock
                    key=showhidden
                    type=bool
                    value={{ dock.showhidden }}
      notify: killall Dock

    - name: UI | Dock | set icon size to {{ dock.icon_size }}
      osx_defaults: domain=com.apple.dock
                    key=tilesize
                    type=float
                    value={{ dock.tilesize }}
      notify: killall Dock

    - name: UI | Dock | auto-hide is {{ dock.autohide }}
      osx_defaults: domain=com.apple.dock
                    key=autohide
                    type=boolean
                    value={{ dock.autohide }}
      notify: killall Dock

    # - name: UI | Keyboard | enable full keyboard access
    #   osx_defaults: domain=NSGlobalDomain
    #                 key=AppleKeyboardUIMode
    #                 type=int
    #                 value=3

    # TODO: see what the current defaults are on a a new machine and if I can live with them
    # - name: UI | Trackpad | enable tap to click
    #   osx_defaults: domain=com.apple.MultiTouchTrackpad
    #                 key=Clicking
    #                 type=boolean
    #                 value=true

    # TODO: enable night shift if not on by default?


- name: Apps (GUI) Configuration
  hosts: all
  tags: apps
  tasks:
    - name: Apps | Safari | Enable Develop menu
      osx_defaults: domain=com.apple.safari
                    key=IncludeDevelopMenu
                    type=boolean
                    value=true

    - name: Apps | Safari | Privacy - 'Prevent cross-site tracking'
      osx_defaults: domain=com.apple.safari
                    key=WebKitStorageBlockingPolicy
                    type=boolean
                    value=true

    - name: Apps | Safari | Privacy - 'Ask websites not to track me'
      osx_defaults: domain=com.apple.safari
                    key=SendDoNotTrackHTTPHeader
                    type=boolean
                    value=true
