---
- name: Docker Development Environment
  hosts: all
  tags: docker

  tasks:
    - name: install Docker for Mac
      homebrew_cask: name=docker state=present

    - name: additional docker tools
      homebrew: name={{ item }} state=present
      with_items: []
